#!/bin/bash

# Function to print an error message and exit
error_exit() {
    echo -e "\033[31mError: $1\033[0m" >&2
    exit 1
}

# Main script

# Check if an argument is provided
if [ $# -ne 1 ]; then
    error_exit "Usage: activate <file_path>"
fi

file_path="$1"

# Resolve the full path of the file
full_path=$(realpath "$file_path") || error_exit "Failed to resolve full path for '$file_path'."

# Check if the file exists
[ -e "$full_path" ] || error_exit "File '$full_path' does not exist."

# Check if execute permission is enabled
if [ -x "$full_path" ]; then
    echo -e "\033[93m$full_path is active\033[0m"
else
    # Add execute permission to the file
    chmod +x "$full_path" && echo -e "$full_path \033[32mACTIVATED\033[0m"
fi
