#!/usr/bin/bash

#& CONFIG
python_script="$HOME/repos/anniv/anniversaries.py"
perl_script="$HOME/bin/enhance-table.pl"
#&

# Read the output into a variable
output=$($python_script "$@")  # parse arguments to manipulate table
# echo $output #~ for debugging

# Check the exit status of the Python script
if [ $? -eq 0 ]; then
    # Python script executed successfully, pass output to Perl script
    echo "$output" | perl "$perl_script"
else
    # Python script failed, print an error message
    echo -e "\033[31mError: Python script failed to execute.\033[0m"
fi
