#!/bin/bash

# Dependencies:
# - ARCHIVES env variable

# TODO: Add config
# TODO: Add to config: archives location (where is it? fetch by file or by env name?)

# Define an associative array to store option descriptions
declare -A option_descriptions=(
    [" "]="Conduct fuzzy search of archives using fzf"
    ["--help"]="Display this help message"
    ["debug"]="Open the script with $EDITOR"
    ["edit"]="Edit document"
    ["git"]="Git commands"
    ["sync"]="Pushes changes to Github"
    ["tree"]="Display the directory tree"
    ["warp"]="[Not implemented] cd to chosen directory"
    ['<command>']="Executes bultin shell command in archives"
    ['<pattern>']="Searches for pattern in tree"
)

# TESTS:
# no arg: passed
# help: passed
# dev: passed
# edit: fail
# tree: passed
# warp: passed
# execute: fail
# launch: pass

main() {
	ARCHIVES="$FILEKEEPER_DIR"
    if [ -z "$ARCHIVES" ]; then warn 'Define $ARCHIVES first.'; exit 1; fi
    if [ ! -d "$ARCHIVES" ]; then warn "Cannot locate $ARCHIVES"; return 2; fi
    
    if [ $# -eq 0 ]; then arch_fzf; fi

    case "$1" in
    	ss) launch_arch_subshell ;;
        ~d | d*bug ) open_this_file ;;
        config ) echo "Not implemented." ;;
        -h | *help ) show_help ;;
        -c | bash  ) shift ; execute_command "$@" ;;
        -g | git   ) shift ; execute_git "$@" ;;
        -l | ls    ) list ;;
        -s | sync  ) push_to_github ;;
        -t | tree  ) arch_tree ;;
        -w | warp | cd) warn "sourcing scripts is bad. Use interactive subshell instead (arch>)" ; cd "$FILEKEEPER_DIR" ;;
        # bash shortcuts
        echo | mkdir | touch | rmdir | rm | bat | cat | yq | md | jq) execute_command "$@" ;;
        # git shortcuts
        diff | status | add | commit | push | pull ) execute_git "$@" ;;
        *) launch_search "$@" ;;
    esac

    # echo -e "\e[31mERROR\e[0m" >&2
    return "$?"
}

arch_fzf() {
    output=$(find "$ARCHIVES" -type f -o -type d | fzf)
    es="$?"
    echo "📋 $style1$output$reset"
    echo "$output" | xclip -selection clipboard
    return $es
}

arch_tree() {
    tree "$ARCHIVES"
    return "$?"
}

execute_command() {
    warn "Not tested"
    if [[ "$1" == '-c' ]]; then shift ; fi
    # Change directory to ~/arch and execute the provided shell commands
    (cd "$ARCHIVES" && eval "$@")
    return $?
}

execute_git(){
	git -C "$ARCHIVES" "$@"
	return "$?"
}

# Help function to display usage information and option descriptions
help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Options:"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
}

launch_search() {
    pattern=""
    
    for arg in "$@"; do
        if [ -z "$pattern" ]; then
            pattern="*$arg*"
        else
            pattern="$pattern|*$arg*"
        fi
    done
    
    # Search using tree command
    output=$(tree $archives_path -C --dirsfirst --prune --matchdirs -P "$pattern")
    
    # Check if the output contains any directories or files
    if [[ $output == *"0 directories, 0 files"* ]]; then
        warn "No match."
        return 0
    else
        echo "$output"
        return 0
    fi
}

list() {
    cd $path
    pwd
    ls
    return 0
}

open_chosen_file() {
    warn Not tested
    # Use eval to expand wildcard pattern in $2
    files=$(eval "ls -d $archives_path/$2")
    
    # Check if any files match the pattern
    if [ -n "$files" ]; then
        # Iterate over the matched files and edit them with the $EDITOR
        for file in $files; do
            $EDITOR "$file"
        done
        return $?
    else
        echo -e "\e[31mNo matching files found.\e[0m"
        return 1
    fi
}

open_this_file() {
    micro $0
    return "$?"
}

push_to_github() {
    git -C "$ARCHIVES" add .
    git -C "$ARCHIVES" commit -m "sent from $NAME"
    git -C "$ARCHIVES" push
    return "$?"
}

show_help() {
    warn "    ~d | d*bug ) open_this_file ;;
    -h | *help ) show_help ;;
    -c | bash  ) shift ; execute_command "$@" ;;
    -g | git   ) shift ; execute_git "$@" ;;
    -l | ls    ) list ;;
    -s | sync  ) push_to_github ;;
    -t | tree  ) arch_tree ;;
    -w | warp  ) cd_to_directory ;;
    # bash shortcuts
    echo | mkdir | touch | rmdir | rm | bat | cat | yq | md | jq) execute_command "$@" ;;
    # git shortcuts
    diff | status | add | commit | push | pull ) execute_git "$@" ;;
    *) launch_search "$@" ;;"
    # return 0
}

warn() { echo -e "\e[1;33m$@\e[0m"; }

main "$@"
