#!/bin/bash

target="$HOME/src/bills"

# Define an associative array to store option descriptions
declare -A option_descriptions=(
    [" "]="______"
    ["debug"]="Debug this script"
    ["help"]="Display a help message"
    ["sync"]="Synchronize with Github"
    ["*"]="Any other patterns executes as task rc:/home/ahmad/.billrc *"
)

main() {
    #warn "This is a warning"

    if [ $# -eq 0 ]; then no_arg_fn; fi

    case "$1" in
        debug) open_this_file ;;
        help | --help) help ;;
        sync) synchronize ;;
        *) execute_and_push "$@" ;;
    esac

    # Process should not reach this point, if it does, maybe forgot exit
    echo -e "\e[31mERROR\e[0m" >&2
    exit 1
}

# Now add functions here in alphabetical order **********************************************

execute_and_push() {
    task rc:"$HOME"/src/.billrc "$@"
    case "$1" in
        ad*|mod*|edit|done|undo|del*) push_to_github "$@" ;;
        start|stop|done) no_arg_fn ;;
        *) exit "$?";;
    esac
}

# Help function to display usage information and option descriptions
help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo -e "\e[96mAdditional functonality to TaskWarrior's overriden task \(bill\)\e[0m"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
    exit 0
}

no_arg_fn() {
    out=$(task rc:"$HOME"/.billrc active 2>&1)
    if [[ "$out" == *"No matches"* ]]; then
        task rc:"$HOME"/.billrc limit:10
        exit "$?"
    else
        task rc:"$HOME"/.billrc active
        exit "$?"
    fi
}

open_this_file() {
    micro $0
    exit "$?"
}

push_to_github() {
    git -C $target add .
    git -C $target commit -m "'$*'" > /dev/null
    git -C $target push
    exit "$?"
}

synchronize() {
    output=$(git -C "$target" pull)
    # Check if the output contains "Already up to date."
    if [[ "$output" == "Already up to date." ]]; then
        # warn "Already up to date. Pushing changes..."
        push_to_github "Sent from $NAME"
    else
        warn "Changes found. Was pull successful\?"
    fi
}

warn() { echo -e "\e[33m$@\e[0m"; }

main "$@"
