#!/bin/bash

# bin directory manager

bin_path="$HOME/bin"

declare -A option_descriptions=(
    [" "]="What happens if no arg given?"
    ["help"]="Display a help message"
    ["debug"]="Opens this script with \$EDITOR"
    ["git"]="Git commands"
    ["add"]="shorcut for bin git add"
    ["commit"]="shortcut for bin git commit"
    ["push"]="shortcut for bin git push"
    ["*"]="Default function"
)

main() {    
    if [ $# -eq 0 ]; then
        cd $bin_path
        pwd
        ls --color
        warn "> bin [help,debug,git,bash,find,status,add,commit,push]"
        exit 0
    fi
    case "$1" in
        -[h]  | help  ) shift ; show_help         ;;
        -[d]  | debug ) shift ; debug_script      ;;
        -[g]  | git   ) shift ; execute_git  "$@" ;;
        -[bx] | bash  ) shift ; execute_bash "$@" ;;
        -[fp] | find  ) shift ; grep_ls      "$@" ;;
        pwd ) cd "$bin_path" ; pwd ;;
        status | diff | add | commit | push ) execute_git "$@" ;;
        *) grep_ls "$@" ;;
    esac
}

# Now add functions here in alphabetical order **********************************************

debug_script() { "$EDITOR" $0 ; exit "$?" ; }

execute_bash(){
    cd $bin_path
    "$@"
    exit "$?"
}

execute_git(){
	git -C $bin_path "$@"
	exit "$?"
}

grep_ls() { ls "$bin_path" | grep --color=always "$@" ; }

# Help function to display usage information and option descriptions
show_help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Options:"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
    exit 0
}

# messages
show_usage() { warn "> bin [help,debug,git,bash,find,status,add,commit,push]"; }
warn(){ echo -e "\e[33m$@\e[0m"; }
err() { echo -e "\e[31m$@\e[0m" 1>&2; }
# ---

main "$@"
