#!/bin/bash

# bin directory manager

warnings() {
    warn "add usage case for each function"
    warn "Concept only.
    documentation incomplete
    functions incomplete"
}

## configurations *********************************
bin_path="$HOME/bin"

# Define an associative array to store option descriptions
# TODO make function for this
declare -A option_descriptions=(
    [" "]="What happens if no arg given?"
    ["help"]="Display a help message"
    ["debug"]="Opens this script with \$EDITOR"
    ["git"]="Git commands"
    ["*"]="Default function"
)

main() {
    DB=$(echo $CONNECTED_DB | cut -d':' -f1)
    target_table=$(echo $CONNECTED_DB | cut -d':' -f2)
    
    if [ $# -eq 0 ]; then default_fn; fi

    case "$1" in
        -h | h?lp  ) shift ; show_help ;; #TODO preserve order
        -D | d*bug ) shift ; debug_this_script ;; # Tested
        -g | git  ) shift ; execute_git "$@";; #untested TODO
        *) default_fn "$@" ;; #TODO
    esac

    # Process should not reach this point, if it does, maybe forgot exit
    echo -e "\e[31mERROR\e[0m" >&2
    exit 1
}

# Now add functions here in alphabetical order **********************************************

debug_this_script() {
    micro $0
    exit "$?"
}

default_fn() {
    warn "no argument means select all "
    warn "* means select all"
    warn "check if $1 matches the name of a table"
    warn "check if $1 matches the name of a column"
    warn "check if $1 is id or rowid"
    warn "check if $* has filter keywords"
    echo "SELECT * FROM $target_table"
    exit 1
}

edit_aliases() {
	"$EDITOR" $HOME/.aliases
	exit "$?"
}

edit_variables() {
	"$EDITOR" $HOME/.variables
	exit "$?"
}

execute_git(){
	warn "--- untested ---"
	echo -e "CURRENT LOCATION: $bin_path"
	git -C $bin_path "$@"
	exit "$?"
}

list_tables() {
    # Test if the string is empty
    if [ -z "$CONNECTED_DB" ]; then
        warn NO CONNECTION
        warn "Do sql connect to connect to db"
    else
        echo "CONNECTED: $DB"
        echo "SELECTED: $target_table"
        err "SELECT ALL TABLES FROM $DB"
    fi
    exit "$?"
}

set_x() {
    case "$1" in
        db) echo "set database $2" ;;
        ta??e*) echo "Set table/target $2" ;;
        *) echo "set $*" ;;
    esac
#    exit 1
}

# Help function to display usage information and option descriptions
show_help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Options:"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
    exit 0
}

show_usage() {
	warn 'edit aliases|variables|debug|help|...'
	exit 1
}

# Messages
warn(){ echo -e "\e[33m$@\e[0m"; }
err() { echo -e "\e[31m$@\e[0m" 1>&2; }

#warnings
main "$@" #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
