#!/bin/bash

# bin directory manager

bin_path="$HOME/bin"

declare -A option_descriptions=(
    [" "]="What happens if no arg given?"
    ["help"]="Display a help message"
    ["debug"]="Opens this script with \$EDITOR"
    ["git"]="Git commands"
    ["add"]="shorcut for bin git add"
    ["commit"]="shortcut for bin git commit"
    ["push"]="shortcut for bin git push"
    ["*"]="Default function"
)

main() {    
    if [ $# -eq 0 ]; then
        cd $bin_path
        pwd
        ls
        exit 0
    fi
    case "$1" in
        -h | h?lp     ) shift ; show_help ;; #TODO preserve order
        -[dD] | d*bug ) shift ; debug_this_script ;;
        -g | git      ) shift ; execute_git "$@" ;;
        status | diff | add | commit | push ) execute_git "$@" ;;
        *) cd $bin_path ; "$@" ; exit "$?" ;;
    esac
}

# Now add functions here in alphabetical order **********************************************

debug_this_script() { "$EDITOR" $0 ; exit "$?" ; }

execute_git(){
	echo -e "CURRENT LOCATION: $bin_path"
	git -C $bin_path "$@"
	exit "$?"
}

# Help function to display usage information and option descriptions
show_help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Options:"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
    exit 0
}

show_usage() {
	warn 'edit aliases|variables|debug|help|...'
	exit 1
}

# Messages
warn(){ echo -e "\e[33m$@\e[0m"; }
err() { echo -e "\e[31m$@\e[0m" 1>&2; }

#warnings
main "$@"
