#!/bin/bash

# Shortcut for frequently modified files

# Define an associative array to store option descriptions
declare -A option_descriptions=(
    [" "]="What happens if no arg given?"
    ["help"]="Display a help message"
    ["debug"]="Opens this script with $EDITOR"
    ["aliases"]="modify ~/.aliases"
    # ["bashrc"]
    ["taskrc"]="$HOME/rc-files/.taskrc"
    ["variables"]="modify ~/.variables"
)

main() {
    #warn "This is a warning"
    
    if [ $# -eq 0 ]; then show_usage; fi

    case "$1" in
        -h | h?lp | --help) show_help ;;
        d?b?g | db?g) debug_this_script ;;
        aliases | al*) edit_aliases ;;
        variables | va*) edit_variables ;;
        *) show_usage "$@" ;;
    esac

    # Process should not reach this point, if it does, maybe forgot exit
    echo -e "\e[31mERROR\e[0m" >&2
    exit 1
}

# Now add functions here in alphabetical order **********************************************

debug_this_script() {
    micro $0
    exit "$?"
}

edit_aliases() {
	"$EDITOR" $HOME/.aliases
	exit "$?"
}

edit_variables() {
	"$EDITOR" $HOME/.variables
	exit "$?"
}

# Help function to display usage information and option descriptions
show_help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Options:"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
    exit 0
}

show_usage() {
	warn 'edit aliases|variables|debug|help|...'
	exit 1
}

warn() { echo -e "\e[33m$@\e[0m"; }

main "$@"
