#!/bin/bash

# get current context from ~/.taskrc
last_line=$(tail -n1 ~/.taskrc)
context=$(awk -F= '{print $2}' <<< "$last_line")
echo $context
# removed context, line removed from ~/.taskrc
source ~/bin/switch_task_context.sh none 2> /dev/null
# retrieve list
task +errand
# reapply context
swch $context 2> /dev/null
# add padding for better presentation
echo ""
