#!/bin/bash

# Define the file path for the guide
guide_file=~/aux/guidance.txt

# Function to print decorations
print_decoration() {
    local decoration="$1"
    local length="$2"
    printf "%*s\n" "$length" "" | tr " " "$decoration"
}

# Function to print text with color
print_color() {
    local text="$1"
    local color="$2"
    printf "\033[${color}m%s\033[0m\n" "$text"
}

# Function to print the guide content with decorations
print_guide() {
    local asterisks_length=60
    print_decoration "*" "$asterisks_length"
    print_color "$(print_color "Guidance:" "1;34")" "1;34" # Coloring "Guidance:"
    echo ''
    while IFS= read -r line; do
        first_word=$(echo "$line" | awk '{print $1}')
        rest_of_line=$(echo "$line" | cut -d ' ' -f 2-)
        print_color "$(print_color "$first_word" "1;31") $rest_of_line" "0;32"
    done < "$guide_file"
    echo ''
    print_color "To modify:     \`mod guide\`" "1;33"
    print_decoration "*" "$asterisks_length"
}

# Main script

# Check if guide file exists
if [ ! -f "$guide_file" ]; then
    echo "Error: Guide file '$guide_file' not found."
    exit 1
fi

# Print the guide content
print_guide

exit 0
