#!/bin/bash

# Wrapper for jrnl

# configs ******************************************************************************************
DOMAIN="$HOME/journal"
cd $DOMAIN
DEBUG=$(cat ".DEBUG")
CONFIG="jrnl.yaml"
CONFIG_WSL="jrnl-WSL.yaml"
CONTEXT=".context"
jrnl="$HOME/.local/pipx/venvs/jrnl/bin/jrnl" # True jrnl
# **************************************************************************************************

# ADD TO STANDARD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# shopt -s extglob
# for arg in apple be cd meet o mississippi
# do
#     # call functions based on arguments
#     case "$arg" in
#         a*             ) foo;;    # matches anything starting with "a"
#         b?             ) bar;;    # matches any two-character string starting with "b"
#         c[de]          ) baz;;    # matches "cd" or "ce"
#         me?(e)t        ) qux;;    # matches "met" or "meet"
#         @(a|e|i|o|u)   ) fuzz;;   # matches one vowel
#         m+(iss)?(ippi) ) fizz;;   # matches "miss" or "mississippi" or others
#         *              ) bazinga;; # catchall, matches anything not matched above
#     esac
# done


function main() {
    # DEFAULT IF NO ARG
    case "$1" in
        "") new_entry "$@" ;;
    esac
    
    # SPECIAL COMMANDS
    case "$1" in
        -\?) print_info ;; # such as context, number of todos, consumed status, etc...
        '.' ) view_journal_today "$@" ;;
        '..') view_journal_yesterday "$@" ;;
        help   | -h) shift; print_help ;;
        debug  | -D) shift; debug_code "$@" ;;
        git    | -g) shift; execute_git "$@" ;;
        config | -C) shift; config_jrnl "$@" ;;
        context| -c) shift; context "$@" ; exit "$?";;
        update | -u) shift; update "$DOMAIN" -add "." -commit "updating from $HOSTNAME" ;;
        push   | +p) shift; push_to_remote ;;
        view   | ?d) view_entries_in_terminal "$@" ;;
        # *) execute_true_jrnl "$@" ;;
    esac
    
    # SHORTCUTS
    case "$1" in
        tags)  shift; execute_true_jrnl --tags ;;
        todo)  shift; execute_true_jrnl "@TODO" "$@" ;;
        del*)  shift; execute_true_jrnl --delete -n "$1" ;;
    esac

    # CATCH-ALL
    case "$1" in
        *) execute_true_jrnl "$@" ;;
    esac
}

# Define an associative array to store option descriptions
declare -A option_descriptions=(
    [" "]="Opens today\'s journal in $VISUAL"
    ["help"]="Display a help message"
    ["debug"]="Opens this script with $EDITOR"
    ["sync"]="synchronize with Github"
    ["read [date]"]="read entry for given date" 
)

config_jrnl() {
    if [[ $(systemd-detect-virt) == "wsl" ]]; then
        "$EDITOR" "$CONFIG_WSL"
    else
        "$EDITOR" "$CONFIG"
    fi
}

context() {
    context_value=$(get_context)
    case "$1" in
        "")                           print_selected_journal=1 ; list_context=1 ;;
        -l | list)                    list_context=1 ;;
        -n | none)                    set_context='none' ;;
        -a | acad | college | school) set_context='academic' ;;
        -w | work)                    set_context='work' ;;
        *)                            warn 'Usage: $ jrnl context [ list | none | acad | work ]'; exit 1 ;;
    esac
    if [[ -n $print_selected_journal ]]; then
        case "$context_value" in
            none)  warn "Primary journal selected." ;;
            acad*) warn "Academic journal selected." ;;
            work)  warn "Work journal selected." ;;
            *)     err  "No journal named $context_value exists." ; exit 1 ;;
        esac
    fi
    if [[ -n $list_context ]]; then
        echo -e "-none\n-academic\n-work"
    fi
    if [[ -n $set_context ]]; then
        echo "$set_context" > "$CONTEXT"
        warn "Context set to [$set_context]"
    fi
}

debug() {
    # show debug message if enabled
    if [[ $DEBUG -eq 1 ]]; then
        echo -e "\e[36m$@\e[0m"
    fi
}

debug_code() {
    if [[ -n "$@" ]]
        then editor="$@"
        else editor="micro"
    fi
    "$editor" "$0"
    exit "$?"
}

execute_git() {
    git -C "$DOMAIN" "$@"
}

execute_true_jrnl() {
    context
    J=$(get_journal)
    "$jrnl" "$J" "$@"
    exit "$?"
    #confirmation code
    # warn "Do you want to execute $jrnl $C $@ ? [Y/n] "
    # read -r answer
    # 
    # if [ -z "$answer" ]; then
        # answer="yes"  # Default to "yes" if user just presses Enter
    # fi
    # 
    # if [ "$answer" == "yes" ] || [ "$answer" == "y" ]; then
        # $jrnl $C $@
    # elif [ "$answer" == "no" ] || [ "$answer" == "n" ]; then
        # echo "Exiting..."
        # # Do nothing, just exit
    # else
        # echo "Invalid input. Defaulting to 'no'."
        # echo "Exiting..."
        # # Do nothing, just exit
    # fi
}

get_context() {
    if [[ ! -f "$CONTEXT" ]]; then
        echo "none" > "$CONTEXT"
        echo "none"
    else
        cat "$CONTEXT"
    fi
}

get_journal() {
    local context=$(get_context)
    case "$context" in
        none)  echo 'primary'; exit 0 ;;
        acad*) echo 'academic'; exit 0 ;;
        work)  echo 'work'; exit 0 ;;
        *) err "No journal associated to $context \!\!"; exit 1 ;;
    esac
}

new_entry() {
    context
    J=$(get_journal)
    "$jrnl" "$J" --config-override editor ""
}

print_info() {
    context
    # more info here
    exit 0
}

# Help function to display usage information and option descriptions
print_help() {
    # # ANSI color codes for colors without using \e[33m and \e[31m
    # GREEN='\033[0;32m'
    # BLUE='\033[0;34m'
    # NC='\033[0m' # No Color
# 
    # echo "Usage: $(basename "$0") [OPTIONS]"
    # echo "Options:"
    # for option in "${!option_descriptions[@]}"; do
        # printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    # done
    # exit 0
    echo 'case "$1" in
            "")   new_entry "$@" ;;
            -?) print_info ;; # such as context
            .) view_journal_today "$@" ;;
            ..) view_journal_yesterday "$@" ;;
            help   | -h) shift; print_help ;;
            debug  | -D) shift; debug_code "$@" ;;
            git    | -g) shift; execute_git "$@" ;;
            config | -C) shift; config_jrnl "$@" ;;
            context| -c) shift; context "$@" ;;
            update | -u) shift; update "$DOMAIN" -add "." -commit "updating from $HOSTNAME" ;;
            push   | +p) shift; push_to_remote ;;
            view   | ?d) view_entries_in_terminal "$@" ;;
            *) execute_true_jrnl "$@" ;;
        esac'
    exit 0
}

push_to_remote() {
    git -C $DOMAIN add .
    git -C $DOMAIN commit -m "updating from $HOSTNAME"
    git -C $DOMAIN push
    exit "$?"
}

view_entries_in_terminal() {
    context
    J=$(get_journal)
    length="${1:0:1}"
    limit="$2"
    debug "d = $length"
    _date=$(date -d "$length days ago" "+%a %b %e %Y")
    debug "date = $_date"
    warn "Viewing entries for $_date"
    "$jrnl" "$J" -on $(date -d "$_date" +%F) -n $limit
    exit "$?"
}

view_journal_today() {
    context
    J=$(get_journal)
    "$jrnl" "$J" -on today --edit
 }

view_journal_yesterday() {
    context
    J=$(get_journal)
    "$jrnl" "$J" -on yesterday --edit
}

warn() { echo -e "\e[33m$@\e[0m"; }
err()  { echo -e "\e[31m$@\e[0m" >&2; }

main "$@"
