#!/bin/bash

QUERY="$@"

[[ -z "$YAML_FILE" ]] && echo -e "Select yaml file by defining variable \$YAML_FILE" && exit 1

# for debugging
  >&2 echo "File: $YAML_FILE"
# >&2 echo "Query: $QUERY"

cat "$YAML_FILE" | yq "$QUERY"
