#!/bin/bash

# Opens a file using the appropriate app

warnings() {
    warn "undeveloped script"
}

# Define an associative array to store option descriptions
declare -A option_descriptions=(
    [" "]="What happens if no arg given?"
    ["help"]="Display a help message"
    ["debug"]="Opens this script with \$EDITOR"
    ["<file>"]="Opens passed file"
)

main() {
    if [ $# -eq 0 ]; then
        show_usage
    fi

    case "$1" in
        h?lp  ) shift ; show_help ;; # Show help
        d*bug ) shift ; debug_this_script ;; # Open script in editor
        *) default_fn "$@" ;; # Open file
    esac

    # Process should not reach this point, if it does, maybe forgot exit
    echo -e "\e[31mERROR\e[0m" >&2
    exit 1
}

# Now add functions here in alphabetical order **********************************************

debug_this_script() {
    ${EDITOR:-nano} $0
    exit "$?"
}

default_fn() {
    local file="$1"
    if [ -z "$file" ]; then
        show_usage
    fi

    if [ ! -f "$file" ]; then
        err "File does not exist: $file"
        exit 1
    fi

    case "${file##*.}" in
        pdf)  gio open "$file" ;;
        odt | doc*) soffice "$file" &;;
        txt)  $VISUAL "$file" ;;
        md)   $VISUAL "$file" ;;
        sh)   $VISUAL "$file" ;;
        py)   $VISUAL "$file" ;;
        *)    $VISUAL "$file" ;; # Default case
    esac

    exit "$?"
}

# Help function to display usage information and option descriptions
show_help() {
    # ANSI color codes for colors without using \e[33m and \e[31m
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m' # No Color

    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Options:"
    for option in "${!option_descriptions[@]}"; do
        printf "  ${GREEN}%-12s${NC} %s\n" "$option" "${option_descriptions[$option]}"
    done
    exit 0
}

show_usage() {
    warn "Usage: $(basename "$0") <file>"
    exit 1
}

# Messages
err()  { echo -e "\e[31m$@\e[0m" 1>&2; }
warn() { echo -e "\e[33m$@\e[0m"; }

main "$@" #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
