#!/bin/bash

sync_home() {
    local msg="$1"
    
    git -C "$HOME" add .
    if [ -n "$msg" ]; then
        git -C "$HOME" commit -m "$msg"
    else
        git -C "$HOME" commit
    fi
    git -C "$HOME" push
}

sync_arch(){
    git -C $HOME/arch add .
    git -C $HOME/arch commit -am "updating arch module" > /dev/null
    git -C $HOME/arch push
}

sync_bill(){}

sync_task(){}

# Check the number of arguments
if [ "$#" -eq 0 ]; then
    sync_home
elif [ "$#" -ge 2 ]; then
    echo "Usage: $0 <option>"
    echo "Options: task, bill, arch"
    exit 1
fi

# Check the argument and perform actions accordingly
case "$1" in
    *task*)
        git -C ~/.task add .
        git -C ~/.task commit -am "updating task module" > /dev/null
        git -C ~/.task push
        git -C $HOME add .task
        git -C $HOME commit -am "updating task module"
        git -C $HOME push
        exit 0
        ;;
    *bill*)
        git -C ~/.bills add .
        git -C ~/.bills commit -am "updating bill module" > /dev/null
        git -C ~/.bills push
        #TODO ******************************
        exit 0
        ;;
    *arch*)
        sync_arch
        exit 0
        ;;
    *)
        echo "Invalid option: $1"
        echo "Available options: task, bill, arch"
        exit 1
        ;;
esac
