#!/bin/bash

echo -e "The following is an example of behaviour only:"
echo -e "SYSTEM: $SYSTEM"
echo -e "CONTEXT: $CONTEXT"
echo -e "CONNECTED TO: $DATABASE"
echo -e "ASSIGNMENTS: overdue"
echo -e "BILLS: overdue"
echo -e "TASKS: overdue"
echo -e "REPOSITORIES: REMOTE OUTDATED"

yellow="\e[93m"
_0="\e[0m"
separator="********************************************************************************"
checkmark="✅"

# Function to check if the output is empty and perform 'git status' accordingly
function check_git_status() {
    local repo_dir="$1"
    local repo_name="$2"
    local status_output=$(git -C "$repo_dir" status -s)
    
    if [[ -z "$status_output" ]]; then
        # If the output is empty, then do 'git status'
        local status_output=$(git -C "$1" status)
        if [[ $status_output == *"Your branch is up to date"* ]]; then
            # echo -e "$yellow$2: $checkmark$_0"
            printf "%-8s: %s\n" "$2" "$checkmark"
        else
            echo -e "${yellow}$repo_name $separator${_0}"
            git -C "$1" status
        fi
    else
        echo -e "${yellow}$repo_name $separator${_0}"
        git -C "$repo_dir" status -s
    fi
}

check_git_status "$HOME/archives" "ARCHIVES"
check_git_status "$HOME/bills" "BILLS"
check_git_status "$HOME/bin" "SCRIPTS"
check_git_status "$HOME/journal" "JOURNAL"
check_git_status "$HOME/.password-store" "SECRETS"
check_git_status "$HOME/rc-files" "RC-FILES"
check_git_status "$HOME/tasks" "TASKS"
