#!/bin/bash

separate() { echo "================================================= $*" ;  }

separate NEXUS
git -C "$NEXUS"  pul 5
separate dotfiles
git -C "$CONFIG" pul 5
separate archives
git -C "$HOME/archives" pul 3
separate scripts
git -C "$HOME/scripts" pul 5
separate pass
git -C "$NEXUS/pass" pul 2
separate coin
git -C "$HOME/src/coinmaster" pul 2
separate jrnl
git -C "$HOME/src/jrnl-wrapper" pul 2
separate

