#!/bin/bash

[[ -z "$NEXUS" ]] && echo 'NEXUS not defined' && exit 1
[[ ! -d "$NEXUS" ]] && echo "$NEXUS ain't a git folder" && exit 2
GIT="git -C $NEXUS"

main() {

	echo -e "***STATUS***"
	$GIT status --short
	
	echo -e "***COMMIT***"
	$GIT add .
	echo 'Added all files for commit'
	$GIT commit --message "committed via $HOSTNAME$0" --verbose
	
	echo -e "***PUSH***" 
	$GIT push --verbose
}

main "$@"
