#!/bin/bash

DATA_HOME="$HOME/data"
GIT="git -C $DATA_HOME"

echo -e "***STATUS***"
$GIT status --short

echo -e "***COMMIT***" 
$GIT commit --all --message "committed via $HOSTNAMEs$0" --verbose

echo -e "***PUSH***" 
$GIT push --verbose
