#!/bin/bash

DATA_HOME="$HOME/data"
GIT="git -C $DATA_HOME"

main() {
	clear -x

	echo -e "***STATUS***"
	$GIT status --short
	
	echo -e "***COMMIT***"
	$GIT add .
	echo 'Added all files for commit'
	$GIT commit --message "committed via $HOSTNAME$0" --verbose
	
	echo -e "***PUSH***" 
	$GIT push --verbose
}

main "$@"
