#!/bin/bash

echo -e "\e[33mConsider adding parser to extract value without key and store in clipboard by passing a single integer\e[0m"

# Function to display usage instructions
function display_usage() {
    echo "Usage: $0 [account_name]"
    echo "Example: $0 google"
}

# Check if no arguments are provided
if [ "$#" -eq 0 ]; then
    pass wallet
    exit $?
fi

# Check if only one argument provided
if [ "$#" -eq 1 ]; then
    pass wallet/"$1"
    exit $?
fi

if [ "$#" -eq 2 ]; then
    pass wallet/"$1" "$2"
    exit $?
fi

# If more than one argument provided, output usage and exit with error
echo "Error: Invalid arguments."
display_usage
exit 1
