#!/bin/bash

open_aot() {
    /mnt/c/"Program Files"/Moz*/firefox.exe "https://aniwatchtv.to/watch/attack-on-titan-112?ep=3315"
}

case "$1" in
    attack) open_aot ;;
    *) echo -e "I don't know what u want..." ;;
esac
