#!/bin/bash

# This is a `task` decorator.

# variables ************************************************************************************
WEEKTAB_FILE="$WEEKTAB_FILE" # a .ods file that must be defined by user
# ********************************************************************************************

main() {
    is_file_exists
    route "$@"
}

is_file_exists(){
    [[ -z "$WEEKTAB_FILE" ]] && warn "Define \$WEEKTAB_FILE" && exit 1
    [[ ! -f "$WEEKTAB_FILE" ]] && warn "No such file: $WEEKTAB_FILE" && exit 2
}

route() {
    case "$1" in
        '') open_file ;;
        open) open_file ;;
    esac
}

open_file() {
    libreoffice "$WEEKTAB_FILE" 2>/dev/null
}

warn() { echo -e "\e[33m$@\e[0m"; }

main "$@"
