#!/bin/bash

# Check if exactly one argument is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <task_id>"
    exit 1
fi

uuid=$(task _get "$1.uuid")
id=$(task _get "$1.id")
description=$(task _get "$1.description")
dir="$HOME/.task/workspace/$uuid"

# Check if directory exists
if [ -d "$dir" ]; then
    cd $dir
    tree .
else
    echo "Directory does not exist for task $1. Creating directory..."
    mkdir -p "$dir"
    task "$uuid" modify dir:$dir
    
    # Create id file
    echo "Id: $id" > "$dir/id"
    echo "Desc: $description" >> "$dir/id"
    echo "id file created at $dir/id"

    # Commit and push to GitHub
    if git -C "$HOME/.task" add . && git -C "$HOME/.task" commit -m "Created new dir" --quiet && git -C "$HOME/.task" push origin master --quiet; then
        echo "Changes committed and pushed to GitHub repository"
    fi
fi
